### ISSUE TITLE
python sftp-server.py --help

### ISSUE THREAD

**Issue by hamdielhamdi** [dlitz/pysftpd#1]
how to fix this : 
xx@xx:~/pysftpd$ python sftp-server.py --help
Traceback (most recent call last):
  File "sftp-server.py", line 26, in <module>
    from sftpd.CLI import CLI
  File "/home/xx/pysftpd/sftpd/__init__.py", line 27, in <module>
    from errors import ProtocolError
ModuleNotFoundError: No module named 'errors'

**Comment by hamdielhamdi** [comment]
done !!
